countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    "Côte d'Ivoire",
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia (Czech Republic)',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesoth',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg	',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (formerly Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',	
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago'
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe']
airports = [
    'Aalborg Airport (AAL)',
    'Aarhus Tirstrup Airport (AAR)',
    'Abilene Municipal Airport (ABI)',
    'Albany Dougherty County Airport (ABY)',
    'Atlantic City International Airport (ACY)',
    'Adelaide Airport (ADL)',
    'Alexandria International Airport (AEX)',
    'Angelholm/Helsingborg Angelholm Airport (AGH)',
    'Augusta Bush Field Airport (AGS)',
    'Auckland International Airport (AKL)',
    'Albany International Airport (ALB)',
    'Amarillo International Airport (AMA)',
    'Amman Queen Alia International Airport (AMM)',
    'Anchorage International Airport (ANC)',
    'Antwerp-Brussels North Airport (ANR)',
    'Apia Faleolo Airport (APW)',
    'Alice Springs Airport (ASP)',
    'Athens Airport (ATH)',
    'Atlanta Hartsfield-Jackson Intl Airport (ATL)',
    'Abu Dhabi International Airport (AUH)',
    'Austin-Bergstrom International Airport (AUS)',
    'Avignon Caumont Airport (AVN)',
    'Akron/Canton Ohio Regional Airport (CAK)',
    'Ankara Esenboga Airport (ESB)',
    "Apia Fagali'i Airport (FGI)",
    "Alpes–Isère Airport (GNB)",
    'Alexandria Borg el Arab Airport (HBE)',
    'Anaa Airport (AAA)'
    'Arrabury Airport(AAB)',
    'Annaba Airport (AAE)',
    'Al Ain Airport (AAN)',
    'Anapa Airport (AAQ)',
    'Altay Airport (AAT)',
    'Araxa Airport (AAX)',
    'Abakan Airport (ABA)',
    'Abadan Airport (ABD)',
    'Allentown/Bethlehem/Easton Airport (ABE)',
    'Abidjan Airport (ABJ)',
    'Ambler Airport (ABL)',
    'Albuquerque Airport (ABQ)',
    'Aberdeen Airport (ABR)',
    'Abu Simbel Airport (ABS)',
    'Al-Baha Airport (ABT)',
    'Abuja Airport (ABV)',
    'Albury Airport (ABX)',
    'Aberdeen Airport (ABZ)',
    'Acapulco Airport (ACA)',
    'Accra Airport (ACC)',
    'Altenrhein Airport (ACH)',
    'Alderney Airport (ACI)',
    'Araracuara Airport (ACR)',
    'Achutupo Airport (ACU)',
    'Arcata/Eureka Airport (ACV)',
    'Adana Airport (ADA)        ',
    'Addis Ababa Airport (ADD)',
    'Adiyaman Airport (ADF)',
    'Adak Island Airport (ADK)',
    'Ardabil Airport (ADU)',
    'Alesund Airport (AES)',
    'Allakaket Airport (AET)',
    'Akureyri Airport (AEY)',
    'Alta Floresta Airport (AFL)',
    'Agadir Airport (AGA)',
    'Agen Airport (AGF)',
    'Angoon Airport (AGN)',
    'Agra Airport (AGR)',
    'Aguascalientes Airport (AGU)',
    'Agatti Island Airport (AGX)',
    'Abha Airport (AHB)Ahe Airport (AHE)',
    'Alghero Airport (AHO)'
    'Al Hoceima Airport (AHU)',
    'Alliance Airport (AIA)',
    'Aitutaki Airport (AIT)',
    'Atiu Island Airport (AIU)',
    'Ajaccio Airport (AJA)',
    'Al Jawf Regional Airport (AJF)',
    'Agri Airport (AJI)',
    'Aizawl Airport (AJL)'
    'Anjouan Airport (AJN)'
    'Arvidsjaur Airport (AJR)',
    'Aracaju Airport (AJU)',
    'Agades Airport (AJY)',
    'Atka Airport (AKB)',
    'Akiak Airport (AKI)',
    'Asahikawa Airport (AKJ)',
    'Anaktuvuk Pass Airport (AKP)',
    'Aksu Airport (AKU)',
    'Akulivik Airport (AKV)',
    'Aktyubinsk Airport (AKX)',
    'Almaty Airport (ALA)',
    'Alicante Airport (ALC)',
    'Alta Airport (ALF)',
    'Algiers Airport (ALG)',
    'Albany Airport (ALH)',
    'Alamosa Airport (ALS)',
    'Ahmedabad Airport (AMD)',
    'Arba Mintch Airport (AMH)',
    'Ambon Airport (AMQ)'
    'Amsterdam Airport (AMS)',
    'Amderma Airport (AMV)',
    'Antofagasta Airport (ANF)',
    'Aniak Airport (ANI)',
    'Andahuaylas Airport (ANS)',
    'Antigua Airport (ANU)',
    'Anvik Airport (ANV)',
    'Andenes Airport (ANX)',
    'Ancona Airport (AOI)',
    'Aomori Airport (AOJ)',
    'Altoona Airport (AOO)',
    'Alor Setar Airport (AOR)',
    'Apataki Airport (APK)',
    'Alpena Airport (APN)',
    'Apartado Airport (APO)',
    'Anqing Airport (AQG)',
    'Aqaba Airport (AQJ)',
    'Arequipa Airport (AQP)',
    'Ann Arbor Airport (ARB)',
    'Arctic Village Airport (ARC)',
    'Alor Island Airport (ARD)',
    'Arkhangelsk Airport (ARH)',
    'Arica Airport (ARI)',
    'Arusha Airport (ARK)',
    'Armidale Airport (ARM)',
    'Aracatuba Airport (ARU)',
    'Ashgabat Airport (ASB)',
    'Aspen Airport (ASE)',
    'Astrakhan Airport (ASF)',
    'Amami O Shima Airport (ASJ)',
    'Asmara Airport (ASM)',
    'Asosa Airport (ASO)',
    'Asuncion Airport (ASU)',
    'Amboseli Airport (ASV)',
    'Aswan Airport (ASW)',
    'Anta-Huaraz/Huascaran Airport (ATA)',
    "Arthur's Town Airport (ATC)",
    'Atoifi Airport (ATD)',
    'Atqasuk Airport (ATK)',
    'Altamira Airport (ATM)',
    'Amritsar Airport (ATQ)',
    'Atmautluak Airport (ATT)',
    'Appleton Airport (ATW)',
    'Assiut Airport (ATZ)',
    'Aruba Airport (AUA)',
    'Arauca Airport (AUC)',
    'Augusta Airport (AUG)',
    'Alakanuk Airport (AUK)',
    'Atuona Airport (AUQ)',
    'Aurillac Airport (AUR)',
    'Aurukun Mission Airport (AUU)',
    'Araguaina Airport (AUX)',
    'Aneityum Airport (AUY)',
    'Anshun Airport (AVA)',
    'Asheville Airport (AVL)',
    'Aniwa Airport (AWD)',
    'Ahvaz International Airport (AWZ)',
    'Anguilla Airport (AXA)',
    'Alexandroupolis Airport (AXD)',
    'Armenia Airport (AXM)',
    'Arutua Airport (AXR)',
    'Akita Airport (AXT)',
    'Axum Airport (AXU)',
    'Ayacucho Airport (AYP)',
    'Ayers Rock Airport (AYQ)',
    'Antalya Airport (AYT)',
    'Andizhan Airport (AZN)',
    'Adrar Airport (AZR)',
    'Aguadilla Airport (BQN)',
    'Awang Airport (CBO)',
    'Antsiranana Airport (DIE)',
    'Anadyr Airport (DYR)',
    'Alotau Airport (GUR)',
    'Atyrau Airport (GUW)',
    'Alahsa Airport (HOF)',
    'Agartala Airport (IXA)',
    'Allahabad (Prayagraj) Airport (IXD)',
    'Aurangabad Airport (IXU)',
    'Aasiaat Airport (JEG)',
    'Astypalaia Island Airport (JTY)',
    'Akiachak Airport (KKI)',
    'A Coruna Airport (LCG)',
    'Almeria Airport (LEI)',
    'Alluitsup Paa Airport (LLU)',
    'Amasya Airport (MZH)',
    'Are/Ostersund Airport (OSD)',
    'Asturias Airport (OVD)',
    'Arar Airport (RAE)',
    'Arua Airport (RUA)',
    'Aktau Airport (SCO)',
    'Antananarivo Airport (TNR)',
    'Astana Airport (TSE)',
    'Aleknagik Airport (WKK)',
    'Anahim Lake Airport (YAA)',
    'Attawapiskat Airport (YAT)',
    'Angling Lake Airport (YAX)',
    'Arviat Airport (YEK)',
    'Aupaluk Airport (YPJ)',
    'Abbotsford Airport (YXX)',
    'Aratika Airport (RKA)',
    'Anglesey Airport (VLY)',
    'Akwa Ibom Airport (QUO)',
    'Alxa Left Banner Bayanhot Airport (AXF)',
    'Alxa Right Banner Badanjilin Airport (RHT)',
    "Arxan Yi'ershi Airport (YIE)",
    'Aldan Airport (ADH)',
    'Asaba International Airport (ABB)',
    'Arak International Airport (AJK)',
    'Antwerpen-Berchem Railway Station (ZYZ)',
    'Aix-en-Provence Aerodrome (QXB)',
    'Ammassivik Heliport (QUW)',
    'Aappilattoq Heliport (Kujalleq) (QUV)',
    'Avesta Krylbo Railway Station (XYP)',
    'Angers – Loire Airport (ANE)',
    'Alitak Seaplane Base (ALZ)',
    'Ashford International Rail Station (QDH)',
    'Angers Airport (QXG)',
    'Avignon TGV Railway Station (XZN)',
    'Akutan Airport (KQA)',
    'Aappilattoq Heliport (AOQ)',
    'Attu Heliport (QGQ)',
    "Anshan Teng'ao Airport (AOG)",
    'Amakusa Airfield (AXJ)',
    'Abu Dhabi Bus Station (ZVJ)',
    'Antwerpen-Centraal railway station (ZWE)',
    'Amsterdam Central Station (ZYA)',
    'Aropa Airport (KIE)',
    'Ann Airport (VBA)',
    'Aek Godang Airport (AEG)',
    "Auki Gwaunaru'u Airport (AKS)",
    'Awasa Airport (AWA)',
    'Antonio Correia Pinto De Macedo Airport (LAJ)',
    'Auguste George Airport (NGD)',
    'Akunnaaq Heliport (QCU)',
    'Arctic Bay Airport (YAB)',
    'Attopeu Airport (AOU)',
    'Arathusa Safari Lodge Airport (ASS)',
    'Ávila Railway Station (AVS)',
    'Abu Dhabi Np Bus Station (XBW)',
    'Ek Bus Station (ZVH)',
    'Albacete Train Station Airport (EEM)',
    'Alicante Train Station (YJE)',
    'Abando Railway Station (YJI)',
    'Almeria Railway Station (AMR)',
    'Aden International Airport (ADE)',
    'Anfa Airport (CAS)',
    'Aristotelis Airport (KSO)',
    'Arnage Airport (LME)',
    'Alberto Carnevalli Airport (MRD)',
    'Augsburg Airport (AGB)',
    'Andi Jemma Airport (MXB)',
    'A. Amilton Beraldo Airport (PGZ)',
    'Al Ghaydah Airport (AAY)',
    'Akhiok Airport (AKK)',
    'Akure Airport (AKR)',
    'Argyle Airport (GYL)',
    'Alcides Fernandez Airport (ACD)',
    'Angama Airport (ANA)',
    'Albacete Bus Station (XJJ)',
    'Altai Airport (LTI)',
    'Aripuanã Airport (AIR)',
    "Andorra–La Seu D'urgell Airport (LEU)",
    'Alferez Fap Vladimir Sara Bauer Airport (AOP)',
    'Adado Airport (AAD)',
    'Ailuk Airport (AIM)',
    'Ailinglaplap Airok Airport (AIC)',
    'Aydın Çıldır Airport (CII)',
    'Atar Airport (ATR)',
    'Arlit Airport (RLT)',
    'Adampur Airport (AIP)',
    'Abéché Airport (AEH)',
    'Abu Musa Airport (AEU)',
    'Abingdon Downs Airport (ABG)',
    'Allegheny County Airport (AGC)',
    'AP Tumenggung Pranoto (AAP)',
    'Al Alamain International Airport (DBB)',
    'Astana Nursultan Nazarbayev International Airport (NQZ)',
    'Addison Airport (ADS)'
    ]
