countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    "Côte d'Ivoire",
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia (Czech Republic)',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesoth',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg	',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (formerly Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago'
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe']
airports = [
    'Aalborg Airport (AAL)',
    'Aarhus Tirstrup Airport (AAR)',
    'Abilene Municipal Airport (ABI)',
    'Albany Dougherty County Airport (ABY)',
    'Atlantic City International Airport (ACY)',
    'Adelaide Airport (ADL)',
    'Alexandria International Airport (AEX)',
    'Angelholm/Helsingborg Angelholm Airport (AGH)',
    'Augusta Bush Field Airport (AGS)',
    'Auckland International Airport (AKL)',
    'Albany International Airport (ALB)',
    'Amarillo International Airport (AMA)',
    'Amman Queen Alia International Airport (AMM)',
    'Anchorage International Airport (ANC)',
    'Antwerp-Brussels North Airport (ANR)',
    'Apia Faleolo Airport (APW)',
    'Alice Springs Airport (ASP)',
    'Athens Airport (ATH)',
    'Atlanta Hartsfield-Jackson Intl Airport (ATL)',
    'Abu Dhabi International Airport (AUH)',
    'Austin-Bergstrom International Airport (AUS)',
    'Avignon Caumont Airport (AVN)',
    'Akron/Canton Ohio Regional Airport (CAK)',
    'Ankara Esenboga Airport (ESB)',
    "Apia Fagali'i Airport (FGI)",
    "Alpes–Isère Airport (GNB)",
    'Alexandria Borg el Arab Airport (HBE)',
    'Anaa Airport (AAA)'
    'Arrabury Airport(AAB)',
    'Annaba Airport (AAE)',
    'Al Ain Airport (AAN)',
    'Anapa Airport (AAQ)',
    'Altay Airport (AAT)',
    'Araxa Airport (AAX)',
    'Abakan Airport (ABA)',
    'Abadan Airport (ABD)',
    'Allentown/Bethlehem/Easton Airport (ABE)',
    'Abidjan Airport (ABJ)',
    'Ambler Airport (ABL)',
    'Albuquerque Airport (ABQ)',
    'Aberdeen Airport (ABR)',
    'Abu Simbel Airport (ABS)',
    'Al-Baha Airport (ABT)',
    'Abuja Airport (ABV)',
    'Albury Airport (ABX)',
    'Aberdeen Airport (ABZ)',
    'Acapulco Airport (ACA)',
    'Accra Airport (ACC)',
    'Altenrhein Airport (ACH)',
    'Alderney Airport (ACI)',
    'Araracuara Airport (ACR)',
    'Achutupo Airport (ACU)',
    'Arcata/Eureka Airport (ACV)',
    'Adana Airport (ADA)        ',
    'Addis Ababa Airport (ADD)',
    'Adiyaman Airport (ADF)',
    'Adak Island Airport (ADK)',
    'Ardabil Airport (ADU)',
    'Alesund Airport (AES)',
    'Allakaket Airport (AET)',
    'Akureyri Airport (AEY)',
    'Alta Floresta Airport (AFL)',
    'Agadir Airport (AGA)',
    'Agen Airport (AGF)',
    'Angoon Airport (AGN)',
    'Agra Airport (AGR)',
    'Aguascalientes Airport (AGU)',
    'Agatti Island Airport (AGX)',
    'Abha Airport (AHB)Ahe Airport (AHE)',
    'Alghero Airport (AHO)'
    'Al Hoceima Airport (AHU)',
    'Alliance Airport (AIA)',
    'Aitutaki Airport (AIT)',
    'Atiu Island Airport (AIU)',
    'Ajaccio Airport (AJA)',
    'Al Jawf Regional Airport (AJF)',
    'Agri Airport (AJI)',
    'Aizawl Airport (AJL)'
    'Anjouan Airport (AJN)'
    'Arvidsjaur Airport (AJR)',
    'Aracaju Airport (AJU)',
    'Agades Airport (AJY)',
    'Atka Airport (AKB)',
    'Akiak Airport (AKI)',
    'Asahikawa Airport (AKJ)',
    'Anaktuvuk Pass Airport (AKP)',
    'Aksu Airport (AKU)',
    'Akulivik Airport (AKV)',
    'Aktyubinsk Airport (AKX)',
    'Almaty Airport (ALA)',
    'Alicante Airport (ALC)',
    'Alta Airport (ALF)',
    'Algiers Airport (ALG)',
    'Albany Airport (ALH)',
    'Alamosa Airport (ALS)',
    'Ahmedabad Airport (AMD)',
    'Arba Mintch Airport (AMH)',
    'Ambon Airport (AMQ)'
    'Amsterdam Airport (AMS)',
    'Amderma Airport (AMV)',
    'Antofagasta Airport (ANF)',
    'Aniak Airport (ANI)',
    'Andahuaylas Airport (ANS)',
    'Antigua Airport (ANU)',
    'Anvik Airport (ANV)',
    'Andenes Airport (ANX)',
    'Ancona Airport (AOI)',
    'Aomori Airport (AOJ)',
    'Altoona Airport (AOO)',
    'Alor Setar Airport (AOR)',
    'Apataki Airport (APK)',
    'Alpena Airport (APN)',
    'Apartado Airport (APO)',
    'Anqing Airport (AQG)',
    'Aqaba Airport (AQJ)',
    'Arequipa Airport (AQP)',
    'Ann Arbor Airport (ARB)',
    'Arctic Village Airport (ARC)',
    'Alor Island Airport (ARD)',
    'Arkhangelsk Airport (ARH)',
    'Arica Airport (ARI)',
    'Arusha Airport (ARK)',
    'Armidale Airport (ARM)',
    'Aracatuba Airport (ARU)',
    'Ashgabat Airport (ASB)',
    'Aspen Airport (ASE)',
    'Astrakhan Airport (ASF)',
    'Amami O Shima Airport (ASJ)',
    'Asmara Airport (ASM)',
    'Asosa Airport (ASO)',
    'Asuncion Airport (ASU)',
    'Amboseli Airport (ASV)',
    'Aswan Airport (ASW)',
    'Anta-Huaraz/Huascaran Airport (ATA)',
    "Arthur's Town Airport (ATC)",
    'Atoifi Airport (ATD)',
    'Atqasuk Airport (ATK)',
    'Altamira Airport (ATM)',
    'Amritsar Airport (ATQ)',
    'Atmautluak Airport (ATT)',
    'Appleton Airport (ATW)',
    'Assiut Airport (ATZ)',
    'Aruba Airport (AUA)',
    'Arauca Airport (AUC)',
    'Augusta Airport (AUG)',
    'Alakanuk Airport (AUK)',
    'Atuona Airport (AUQ)',
    'Aurillac Airport (AUR)',
    'Aurukun Mission Airport (AUU)',
    'Araguaina Airport (AUX)',
    'Aneityum Airport (AUY)',
    'Anshun Airport (AVA)',
    'Asheville Airport (AVL)',
    'Aniwa Airport (AWD)',
    'Ahvaz International Airport (AWZ)',
    'Anguilla Airport (AXA)',
    'Alexandroupolis Airport (AXD)',
    'Armenia Airport (AXM)',
    'Arutua Airport (AXR)',
    'Akita Airport (AXT)',
    'Axum Airport (AXU)',
    'Ayacucho Airport (AYP)',
    'Ayers Rock Airport (AYQ)',
    'Antalya Airport (AYT)',
    'Andizhan Airport (AZN)',
    'Adrar Airport (AZR)',
    'Aguadilla Airport (BQN)',
    'Awang Airport (CBO)',
    'Antsiranana Airport (DIE)',
    'Anadyr Airport (DYR)',
    'Alotau Airport (GUR)',
    'Atyrau Airport (GUW)',
    'Alahsa Airport (HOF)',
    'Agartala Airport (IXA)',
    'Allahabad (Prayagraj) Airport (IXD)',
    'Aurangabad Airport (IXU)',
    'Aasiaat Airport (JEG)',
    'Astypalaia Island Airport (JTY)',
    'Akiachak Airport (KKI)',
    'A Coruna Airport (LCG)',
    'Almeria Airport (LEI)',
    'Alluitsup Paa Airport (LLU)',
    'Amasya Airport (MZH)',
    'Are/Ostersund Airport (OSD)',
    'Asturias Airport (OVD)',
    'Arar Airport (RAE)',
    'Arua Airport (RUA)',
    'Aktau Airport (SCO)',
    'Antananarivo Airport (TNR)',
    'Astana Airport (TSE)',
    'Aleknagik Airport (WKK)',
    'Anahim Lake Airport (YAA)',
    'Attawapiskat Airport (YAT)',
    'Angling Lake Airport (YAX)',
    'Arviat Airport (YEK)',
    'Aupaluk Airport (YPJ)',
    'Abbotsford Airport (YXX)',
    'Aratika Airport (RKA)',
    'Anglesey Airport (VLY)',
    'Akwa Ibom Airport (QUO)',
    'Alxa Left Banner Bayanhot Airport (AXF)',
    'Alxa Right Banner Badanjilin Airport (RHT)',
    "Arxan Yi'ershi Airport (YIE)",
    'Aldan Airport (ADH)',
    'Asaba International Airport (ABB)',
    'Arak International Airport (AJK)',
    'Antwerpen-Berchem Railway Station (ZYZ)',
    'Aix-en-Provence Aerodrome (QXB)',
    'Ammassivik Heliport (QUW)',
    'Aappilattoq Heliport (Kujalleq) (QUV)',
    'Avesta Krylbo Railway Station (XYP)',
    'Angers – Loire Airport (ANE)',
    'Alitak Seaplane Base (ALZ)',
    'Ashford International Rail Station (QDH)',
    'Angers Airport (QXG)',
    'Avignon TGV Railway Station (XZN)',
    'Akutan Airport (KQA)',
    'Aappilattoq Heliport (AOQ)',
    'Attu Heliport (QGQ)',
    "Anshan Teng'ao Airport (AOG)",
    'Amakusa Airfield (AXJ)',
    'Abu Dhabi Bus Station (ZVJ)',
    'Antwerpen-Centraal railway station (ZWE)',
    'Amsterdam Central Station (ZYA)',
    'Aropa Airport (KIE)',
    'Ann Airport (VBA)',
    'Aek Godang Airport (AEG)',
    "Auki Gwaunaru'u Airport (AKS)",
    'Awasa Airport (AWA)',
    'Antonio Correia Pinto De Macedo Airport (LAJ)',
    'Auguste George Airport (NGD)',
    'Akunnaaq Heliport (QCU)',
    'Arctic Bay Airport (YAB)',
    'Attopeu Airport (AOU)',
    'Arathusa Safari Lodge Airport (ASS)',
    'Ávila Railway Station (AVS)',
    'Abu Dhabi Np Bus Station (XBW)',
    'Ek Bus Station (ZVH)',
    'Albacete Train Station Airport (EEM)',
    'Alicante Train Station (YJE)',
    'Abando Railway Station (YJI)',
    'Almeria Railway Station (AMR)',
    'Aden International Airport (ADE)',
    'Anfa Airport (CAS)',
    'Aristotelis Airport (KSO)',
    'Arnage Airport (LME)',
    'Alberto Carnevalli Airport (MRD)',
    'Augsburg Airport (AGB)',
    'Andi Jemma Airport (MXB)',
    'A. Amilton Beraldo Airport (PGZ)',
    'Al Ghaydah Airport (AAY)',
    'Akhiok Airport (AKK)',
    'Akure Airport (AKR)',
    'Argyle Airport (GYL)',
    'Alcides Fernandez Airport (ACD)',
    'Angama Airport (ANA)',
    'Albacete Bus Station (XJJ)',
    'Altai Airport (LTI)',
    'Aripuanã Airport (AIR)',
    "Andorra–La Seu D'urgell Airport (LEU)",
    'Alferez Fap Vladimir Sara Bauer Airport (AOP)',
    'Adado Airport (AAD)',
    'Ailuk Airport (AIM)',
    'Ailinglaplap Airok Airport (AIC)',
    'Aydın Çıldır Airport (CII)',
    'Atar Airport (ATR)',
    'Arlit Airport (RLT)',
    'Adampur Airport (AIP)',
    'Abéché Airport (AEH)',
    'Abu Musa Airport (AEU)',
    'Abingdon Downs Airport (ABG)',
    'Allegheny County Airport (AGC)',
    'AP Tumenggung Pranoto (AAP)',
    'Al Alamain International Airport (DBB)',
    'Astana Nursultan Nazarbayev International Airport (NQZ)',
    'Addison Airport (ADS)'
    'Jakarta Soekarno-Hatta Airport (CGK)',
    'Jeju International Airport (CJU)',
    'Jackson-Evers International Airport (JAN)',
    'Jacksonville International Airport (JAX)',
    'Johannesburg O.R. Tambo International Airport (JNB)',
    'Jambi Airport (DJB)',
    'Jayapura Airport (DJJ)',
    'Jazan Airport (GIZ)',
    'Jijel Airport (GJL)',
    'Jinju Airport (HIN)',
    'Johannesburg Lanseria International Airport (HLA)',
    'Jammu Airport (IXJ)',
    'Jackson Airport (JAC)',
    'Jaipur Airport (JAI)',
    'Jalapa Airport (JAL)',
    'Jauja Airport (JAU)',
    'Jonesboro Airport (JBR)',
    'Julia Creek Airport (JCK)',
    'Jodhpur Airport (JDH)',
    'Juazeiro Do Norte Airport (JDO)',
    'Jingdezhen Airport (JDZ)',
    'Jersey Airport (JER)',
    'Jamnagar Airport (JGA)',
    'Jiayuguan Airport (JGN)',
    'Jinggangshan (Ji an) Airport (JGS)',
    'Jinghong Airport (JHG)',
    'Jamestown Airport (JHW)',
    'Jijiga Airport (JIJ)',
    'Jimma Airport (JIM)',
    'Jinjiang Airport (JJN)',
    'Jonkoping Airport (JKG)',
    'Janakpur Airport (JKR)',
    'Joplin Airport (JLN)',
    'Jabalpur Airport (JLR)',
    'Jamestown Airport (JMS)',
    'Jiamusi Airport (JMU)',
    'Jining Airport (JNG)',
    'Juneau Airport (JNU)',
    'Jinzhou Airport (JNZ)',
    'Joensuu Airport (JOE)',
    'Joinville Airport (JOI)',
    'Jos Airport (JOS)',
    'Joao Pessoa Airport (JPA)',
    'Ji-Parana Airport (JPR)',
    'Jaque Airport (JQE)',
    'Jorhat Airport (JRH)',
    'Jessore Airport (JSR)',
    'Johnstown Airport (JST)',
    'Juba Airport (JUB)',
    'Jujuy Airport (JUJ)',
    'Juliaca Airport (JUL)',
    'Jyvaskyla Airport (JYV)',
    'Jiuzhaigou (Huanglong) Airport (JZH)',
    'Jackson Airport (MKL)',
    'Jacksonville Airport (OAJ)',
    'Jinan Airport (TNA)',
    'Jerez Airport (XRY)',
    'Jixi Airport (JXA)',
    'Jakarta Halim Perdanakusuma Airport (HLP)',
    'Jember Noto Hadinegoro Airport (JBB)',
    'Jinchang Jinchuan Airport (JIC)',
    'Jiagedaqi Airport (JGD)',
    'Jaguaruna Regional Airport (JJG)',
    'José Aponte de la Torre Airport (NRR)',
    'Jiaxing Airport (JXS)',
    'Jaime González Airport (CFG)',
    'Jacksonville Amtrak Station (ZUJ)',
    'Juan Mendoza Airport (ORU)',
    'Jaén Airport (JAE)',
    'Jomsom Airport (JMO)',
    'Jorge Isaacs Airport (MCJ)',
    'Jerez Railway Stn (YJW)',
    'Jasper Railway Station (XDH)',
    'Jonquiere Rail Station (XJQ)',
    'Lushan Airport (JIU)',
    'Jaisalmer Airport (JSA)',
    'Jumla Airport (JUM)',
    'Jiroft Airport (JYR)',
    'Juan V. Gomez Intl Airport (SVZ)',
    'Jose F. Bermudez Airport (CUP)',
    'Juan H. White Airport (CAQ)',
    'Jeki Airstrip (JEK)',
    'Juína Airport (JIA)',
    'Jericoacoara Airport (JJD)',
    'Jeh Airport (JEJ)',
    'Jalalabad Airport (JAA)',
    'Jaluit Airport (UIT)',
    'Jahrom Airport (JAR)',
    'Jiansanjiang Airport (JSJ)',
    'Jindal Vijaynagar Airport (VDY)',
    'J. F. Mitchell Airport (BQU)',
    'Jicalapa Airport (GUO)',
    'Japura Airport (RGT)',
    'Jacarepaguá Airport (RRJ)',
    'Jos Orno Imsula Airport (JIO)',
    'Jagdalpur Airport (JGB)',
    'Jérémie Airport (JEE)',
    'Jalgaon Airport (JLG)',
    'Jeypore Airport (PYB)',
    'Jamshedpur Sonari Airport (IXW)',
    'Kanas Airport (KJI)',
    'Kavalerovo Airport (KVR)',
    'Kulyab Airport (TJU)',
    'Kasiguncu Airport (PSJ)',
    'Kooddoo Airport (GKK)',
    'Kaili Huangping Airport (KJH)',
    'Kirovsk-Apatity Airport (KVK)',
    'Kapiti Coast Airport (PPQ)',
    'Kangding Airport (KGT)',
    'Koro Airport (KXF)',
    'Kangersuatsiaq Heliport (KGQ)',
    'King Mswati III International Airport (SHO)',
    'Klagenfurt Main station (KGV)',
    'Kokshetau Airport (KOV)',
    'Kyzyl Airport (KYZ)',
    'Kilaguni Airport (ILU)',
    'Kullorsuaq Heliport (KHQ)',
    'Kalaeloa Airport (JRF)',
    'Kherson International Airport (KHE)',
    'Kingston Rail Station (XEG)',
    'Kalemie Airport (FMI)',
    'Kuummiit Heliport (KUZ)',
    'Kasama Airport (KAA)',
    'Kurgan Airport (KRO)',
    'Kithira Airport (KIT)',
    'Kamembe Airport (KME)',
    'Kitsissuarsuit Heliport (QJE)',
    'Kariba Airport (KAB)',
    'Kasese Airport (KSE)',
    'Korhogo Airport (HGO)',
    'Kastamonu Airport (KFS)',
    'Khatanga Airport (HTG)',
    'Kangaatsiaq Heliport (QPW)',
    'Kikaiga Shima (KKX)',
    'Kirensk Airport (KCK)',
    'Kihihi Airport (KHX)',
    'Kilwa Masoko Airport (KIY)',
    'Kaluga (Grabtsevo) Airport (KLF)',
    'Koulamoutou Airport (KOU)',
    'Kitadaito Airport (KTD)',
    'Karluk Lake Seaplane Base (KKL)',
    'Karlsruhe Train Station (KJR)',
    'Kunshannan Railway Station (KVN)',
    'Kinshasa Central Railway Station (FIS)',
    'Kuressaare Airport (URE)',
    'Kabri Dar Airport (ABK)',
    'Kelani-Peliyagooda SPB (KEZ)',
    'Kaitaia Airport (KAT)',
    'Kandy Airport (KDW)',
    'Kanpur Airport (KNU)',
    'Kyoto Station (UKY)',
    'Kankesanturai Airport (JAF)',
    'Kake Sea Plane Base (KAE)',
    'Kardla Airport (KDL)',
    'Khorramabad Airport (KHD)',
    'Kauehi Airport (KHZ)',
    'Kamina-Ville Airport (KMN)',
    'Kolwezi Airport (KWZ)',
    'Katiu Airport (KXU)',
    'Karluk Airport (KYK)',
    'Kuito Airport (SVP)',
    'Katsina Airport (DKA)',
    'Keekorok Airport (KEU)',
    'Khurba Airport (KXK)',
    'King Khalid Military City Airport (KMC)',
    'Khatgal Airport (HTM)',
    'Kokhanok Airport (KNK)',
    'Keperveyem Airport (KPW)',
    'Kaufana Airport (EUA)',
    'Kirawira B Airport (GTZ)',
    'Kalabo Airport (KLB)',
    'Kings Creek Station Airport (KCS)',
    'Kubin Airport (KUG)',
    'Kelsey Airport (KES)',
    'Komo Airport (KOM)',
    'Kitui Bay Sea Plane Base (KKB)',
    'Kings Cross Railway Station (QQK)',
    'Karumba Airport (KRB)',
    'Kolda North Airport (KDA)',
    'Kufra Airport (AKF)',
    'Kismayo Airport (KMU)',
    'Kaikoura Airport (KBZ)',
    'Kandla Airport (IXY)',
    'Kazi Nazrul Islam Airport (RDP)',
    'Kindu Airport (KND)',
    'Kili Airport (KIO)',
    'Kichwa Tembo Airport (KTJ)',
    'Kempsey Airport (KPS)',
    'Kolhapur Airport (KLH)',
    'Kalat Airport (KBH)',
    'Khark Island Airport (KHK)',
    'Kashan International Airport (KKS)',
    'Kalaleh Airport (KLM)',
    'Kunovice Airport (UHE)',
    'Kishangarh Airport (KQH)',
    'Kannur International Airport (CNN)',
    'Kertajati International Airport (KJT)',
    'Kulhudhuffushi (HDK)',
    'Keshod Airport (IXK)',
    'Kurnool Airport (KJB)',
    'Kapanga Airport (KAP)',
    'Kushinagar Airport (KBK)'
    ]
